package com.ainosoft.server;

// Generated 12 Mar, 2015 4:39:52 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.GenericGenerator;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "Address", catalog = "address_db")
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY, region="Address")
public class Address implements java.io.Serializable {

	private int idAddress;
	private String country;
	private String state;
	private String city;
	private String street;
	private String zip;
	private String name;

	public Address() {
	}

	public Address(int idAddress) {
		this.idAddress = idAddress;
	}

	public Address(String country, String state, String city,
			String street, String zip, String name) {
		
		this.country = country;
		this.state = state;
		this.city = city;
		this.street = street;
		this.zip = zip;
		this.name = name;
	}


	@Id
	@GenericGenerator(name="id_generator",strategy="increment")
	@GeneratedValue(generator="id_generator")
	@Column(name = "idAddress", unique = true, nullable = false)
	public int getIdAddress() {
		return this.idAddress;
	}

	public void setIdAddress(int idAddress) {
		this.idAddress = idAddress;
	}

	@Column(name = "country", length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "street", length = 45)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "zip", length = 45)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
